export const CONTACT_INFO_FAILED = "CONTACT_INFO_FAILED";
export const CONTACT_INFO_FETCHED = "CONTACT_INFO_FETCHED";
export const CONTACT_INFO_FETCHING = "CONTACT_INFO_FETCHING";
export const CONTACT_INFO_INVALID = "CONTACT_INFO_INVALID";
export const ADD_TO_BLACKLIST = "ADD_TO_BLACKLIST";
export const CHANGE_SEARCHTERM = "CHANGE_SEARCHTERM";